package ruapps

import "strings"

// Packages lists Android package names of popular Russian apps that
// should bypass a VPN proxy so they can reach domestic services directly.
var Packages = []string{
	// Banking & finance
	"ru.sberbankmobile",
	"ru.sberbankmobile.investment",
	"ru.sberbank.sberbankid",
	"ru.sberbank.spasibo",
	"ru.alfabank.mobile.android",
	"ru.alfabank.oavdo.alfadirect",
	"ru.tinkoff.investing",
	"ru.tinkoff.android.business",
	"com.idamob.tinkoff.android",
	"ru.vtb24.mobilebanking.android",
	"ru.vtb.invest",
	"ru.raiffeisennews",
	"ru.gazprombank.android",
	"com.openbank",
	"ru.sovcombank.halva",
	"ru.psbank.online",
	"ru.rshb.dbo",
	"ru.mkb.mobile",
	"ru.bspb.android",
	"ru.homecredit.mycredit",
	"ru.mw",
	"ru.otpbank.mobile",
	"ru.unicredit.android",
	"ru.akbars.android",
	"com.ubrir.app",
	"ru.letobank.Prometheus",
	"ru.uralsibbank.android",
	"ru.rosbank.android",
	"com.bm.android",
	"ru.yoomoney.android",
	"ru.nspk.mirpay",

	// Government & public services
	"ru.rostel",
	"ru.gosuslugi.pos",
	"ru.fns.lkfl",
	"com.gnivts.selfemployed",
	"ru.mos.app",
	"ru.mos.parking.new",
	"ru.mos.transport",
	"ru.mos.polls",

	// Yandex ecosystem
	"ru.yandex.searchplugin",
	"com.yandex.browser",
	"com.yandex.browser.lite",
	"ru.yandex.taxi",
	"ru.yandex.market",
	"ru.yandex.music",
	"ru.yandex.disk",
	"ru.yandex.eda",
	"com.yandex.launcher",
	"ru.yandex.weatherplugin",
	"com.yandex.maps",
	"ru.yandex.mail",
	"ru.yandex.translate",
	"com.yandex.mobile.drive",
	"ru.yandex.autoru",
	"ru.yandex.deliveryapp",
	"ru.yandex.yandexnavi",
	"com.yandex.iot",

	// E-commerce & marketplaces
	"com.wildberries.ru",
	"com.avito.android",
	"ru.ozon.app.android",
	"ru.ozon.seller",
	"ru.detmir.app",
	"ru.lamoda.android",
	"com.joom",
	"ru.mvideo.app",
	"ru.dns.shop.android",
	"ru.citilink.app",
	"ru.sportmaster.app",
	"ru.letoile.android",
	"com.letu.android",
	"ru.goldapple.buyers",
	"ru.apteka",
	"ru.getpharma.eapteka",
	"ru.leroymerlin.mobile",
	"ru.megamarket.marketplace",
	"com.allgoritm.youla",
	"ru.vseinstrumenti.app",

	// Social, messaging & media
	"com.vkontakte.android",
	"ru.ok.android",
	"ru.oneme.app",
	"ru.rutube.app",
	"ru.zen.android",
	"ru.ivi.client",
	"ru.kinopoisk",
	"ru.mts.music.android",
	"ru.more.play",
	"ru.start.androidmobile",
	"ru.wink.android",
	"ru.premier.app",
	"ru.kion.app",
	"ru.smotrim.app",
	"com.vk.calls",
	"com.vk.im",
	"com.vk.music",
	"ru.zvuk.app",
	"ru.litres.android.reader",
	"ru.litres.android.listen",
	"ru.mybook.reader",

	// Food, groceries & delivery
	"com.deliveryclub",
	"ru.samokat.app",
	"ru.lenta.app",
	"ru.vkusvill",
	"ru.pyaterochka.app",
	"ru.perekrestok.app",
	"ru.magnit.app.buyer",
	"ru.sbermarket.app",
	"ru.bestprice.fixprice",
	"ru.dodo.pizza",

	// Transport & travel
	"ru.aviasales",
	"ru.rzd.passenger",
	"ru.mosgorpass",
	"ru.autodoc.autodocapp",
	"ru.dublgis.dgismobile",
	"com.tutu.railway",
	"ru.cian.main",
	"ru.domclick.app",
	"ru.s7.android",
	"ru.aeroflot.app",
	"ru.pobeda.app",
	"com.punicapp.whoosh",
	"ru.urentbike.app",

	// Mobile carriers
	"ru.megafon.mlk",
	"ru.mts.mymts",
	"ru.beeline.services",
	"ru.tele2.mytele2",
	"ru.yota.android",
	"ru.rt.android",

	// Utilities & productivity
	"ru.mail.cloud",
	"ru.mail.mailapp",
	"com.my.mail",
	"com.logistic.sdek",
	"com.octopod.russianpost.client.android",
	"ru.hh.android",
	"com.kaspersky.kes",
	"com.drweb.pro",
	"com.gismeteo",

	// Health
	"com.programmisty.emiasapp",
	"com.platfomni.gorzdrav",
	"com.invitro.app",
}

// Joined returns all package names as a comma-separated string.
func Joined() string {
	return strings.Join(Packages, ",")
}
